* merge from 0.8.3   * Added sample site code.
git-svn-id: http://svn.sourceforge.jp/svnroot/modchxj/mod_chxj/trunk@1826 1a406e8e-add9-4483-a2c8-d8cac5b7c224

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -872,9 +872,12 @@ FFLAGS
 ac_ct_F77
 LIBTOOL
 APXS
+APXS2
 WAND_CONFIG
 APR_CONFIG
+APR_1_CONFIG
 APU_CONFIG
+APU_1_CONFIG
 with_apache_header
 QDEFS
 DDEFS
@@ -5443,7 +5446,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 5446 "configure"' > conftest.$ac_ext
+  echo '#line 5449 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7940,11 +7943,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7943: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7946: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7947: \$? = $ac_status" >&5
+   echo "$as_me:7950: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8208,11 +8211,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8211: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8214: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:8215: \$? = $ac_status" >&5
+   echo "$as_me:8218: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8312,11 +8315,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8315: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8318: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:8319: \$? = $ac_status" >&5
+   echo "$as_me:8322: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -10609,7 +10612,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10612 "configure"
+#line 10615 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10709,7 +10712,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10712 "configure"
+#line 10715 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13045,11 +13048,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13048: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13051: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13052: \$? = $ac_status" >&5
+   echo "$as_me:13055: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -13149,11 +13152,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13152: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13155: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13156: \$? = $ac_status" >&5
+   echo "$as_me:13159: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14710,11 +14713,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14713: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14716: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14717: \$? = $ac_status" >&5
+   echo "$as_me:14720: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -14814,11 +14817,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14817: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14820: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14821: \$? = $ac_status" >&5
+   echo "$as_me:14824: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -17001,11 +17004,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17004: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17007: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17008: \$? = $ac_status" >&5
+   echo "$as_me:17011: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17269,11 +17272,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17272: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17275: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17276: \$? = $ac_status" >&5
+   echo "$as_me:17279: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17373,11 +17376,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17376: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17379: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:17380: \$? = $ac_status" >&5
+   echo "$as_me:17383: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -20248,10 +20251,57 @@ fi
 
 
   if test "x$APXS" = "xno"; then
-      { { echo "$as_me:$LINENO: error: apxs not found." >&5
+      # Extract the first word of "apxs2", so it can be a program name with args.
+set dummy apxs2; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_path_APXS2+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $APXS2 in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_APXS2="$APXS2" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+as_dummy="/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/usr/local/apache/bin"
+for as_dir in $as_dummy
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_path_APXS2="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+  test -z "$ac_cv_path_APXS2" && ac_cv_path_APXS2="no"
+  ;;
+esac
+fi
+APXS2=$ac_cv_path_APXS2
+if test -n "$APXS2"; then
+  { echo "$as_me:$LINENO: result: $APXS2" >&5
+echo "${ECHO_T}$APXS2" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+      if test "x$APXS2" = "xno" ; then
+        { { echo "$as_me:$LINENO: error: apxs not found." >&5
 echo "$as_me: error: apxs not found." >&2;}
    { (exit 1); exit 1; }; }
+      fi
   fi
+fi
+if test "x$APXS2" != "x" ; then
+  APXS="$APXS2"
 fi
 if test "x$with_apxs" != "x" ; then
   APXS=$with_apxs
@@ -20403,12 +20453,12 @@ fi
 set dummy apr-1-config; ac_word=$2
 { echo "$as_me:$LINENO: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
-if test "${ac_cv_path_APR_CONFIG+set}" = set; then
+if test "${ac_cv_path_APR_1_CONFIG+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-  case $APR_CONFIG in
+  case $APR_1_CONFIG in
   [\\/]* | ?:[\\/]*)
-  ac_cv_path_APR_CONFIG="$APR_CONFIG" # Let the user override the test with a path.
+  ac_cv_path_APR_1_CONFIG="$APR_1_CONFIG" # Let the user override the test with a path.
   ;;
   *)
   as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
@@ -20419,7 +20469,7 @@ do
   test -z "$as_dir" && as_dir=.
   for ac_exec_ext in '' $ac_executable_extensions; do
   if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
-    ac_cv_path_APR_CONFIG="$as_dir/$ac_word$ac_exec_ext"
+    ac_cv_path_APR_1_CONFIG="$as_dir/$ac_word$ac_exec_ext"
     echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
     break 2
   fi
@@ -20427,24 +20477,26 @@ done
 done
 IFS=$as_save_IFS
 
-  test -z "$ac_cv_path_APR_CONFIG" && ac_cv_path_APR_CONFIG="no"
+  test -z "$ac_cv_path_APR_1_CONFIG" && ac_cv_path_APR_1_CONFIG="no"
   ;;
 esac
 fi
-APR_CONFIG=$ac_cv_path_APR_CONFIG
-if test -n "$APR_CONFIG"; then
-  { echo "$as_me:$LINENO: result: $APR_CONFIG" >&5
-echo "${ECHO_T}$APR_CONFIG" >&6; }
+APR_1_CONFIG=$ac_cv_path_APR_1_CONFIG
+if test -n "$APR_1_CONFIG"; then
+  { echo "$as_me:$LINENO: result: $APR_1_CONFIG" >&5
+echo "${ECHO_T}$APR_1_CONFIG" >&6; }
 else
   { echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6; }
 fi
 
 
-    if test "x$APR_CONFIG" = "xno" ; then
-      { { echo "$as_me:$LINENO: error: apr-config not found." >&5
-echo "$as_me: error: apr-config not found." >&2;}
+    if test "x$APR_1_CONFIG" = "xno" ; then
+      { { echo "$as_me:$LINENO: error: apr-config and apr-1-config not found." >&5
+echo "$as_me: error: apr-config and apr-1-config not found." >&2;}
    { (exit 1); exit 1; }; }
+    else
+      APR_CONFIG="$APR_1_CONFIG"
     fi
   fi
 fi
@@ -20500,12 +20552,12 @@ fi
 set dummy apu-1-config; ac_word=$2
 { echo "$as_me:$LINENO: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
-if test "${ac_cv_path_APU_CONFIG+set}" = set; then
+if test "${ac_cv_path_APU_1_CONFIG+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-  case $APU_CONFIG in
+  case $APU_1_CONFIG in
   [\\/]* | ?:[\\/]*)
-  ac_cv_path_APU_CONFIG="$APU_CONFIG" # Let the user override the test with a path.
+  ac_cv_path_APU_1_CONFIG="$APU_1_CONFIG" # Let the user override the test with a path.
   ;;
   *)
   as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
@@ -20516,7 +20568,7 @@ do
   test -z "$as_dir" && as_dir=.
   for ac_exec_ext in '' $ac_executable_extensions; do
   if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
-    ac_cv_path_APU_CONFIG="$as_dir/$ac_word$ac_exec_ext"
+    ac_cv_path_APU_1_CONFIG="$as_dir/$ac_word$ac_exec_ext"
     echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
     break 2
   fi
@@ -20524,30 +20576,33 @@ done
 done
 IFS=$as_save_IFS
 
-  test -z "$ac_cv_path_APU_CONFIG" && ac_cv_path_APU_CONFIG="no"
+  test -z "$ac_cv_path_APU_1_CONFIG" && ac_cv_path_APU_1_CONFIG="no"
   ;;
 esac
 fi
-APU_CONFIG=$ac_cv_path_APU_CONFIG
-if test -n "$APU_CONFIG"; then
-  { echo "$as_me:$LINENO: result: $APU_CONFIG" >&5
-echo "${ECHO_T}$APU_CONFIG" >&6; }
+APU_1_CONFIG=$ac_cv_path_APU_1_CONFIG
+if test -n "$APU_1_CONFIG"; then
+  { echo "$as_me:$LINENO: result: $APU_1_CONFIG" >&5
+echo "${ECHO_T}$APU_1_CONFIG" >&6; }
 else
   { echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6; }
 fi
 
 
-    if test "x$APU_CONFIG" = "xno" ; then
-      { { echo "$as_me:$LINENO: error: apu-config not found." >&5
-echo "$as_me: error: apu-config not found." >&2;}
+    if test "x$APU_1_CONFIG" = "xno" ; then
+      { { echo "$as_me:$LINENO: error: apu-config and apu-1-config not found." >&5
+echo "$as_me: error: apu-config and apu-1-config not found." >&2;}
    { (exit 1); exit 1; }; }
+    else
+      APU_CONFIG="$APU_1_CONFIG"
     fi
   fi
 fi
 if test "x$with_apu_config" != "x" ; then
   APU_CONFIG=$with_apu_config
 fi
+
 
 
 # Check whether --with-iconv was given.
@@ -22848,9 +22903,12 @@ FFLAGS!$FFLAGS$ac_delim
 ac_ct_F77!$ac_ct_F77$ac_delim
 LIBTOOL!$LIBTOOL$ac_delim
 APXS!$APXS$ac_delim
+APXS2!$APXS2$ac_delim
 WAND_CONFIG!$WAND_CONFIG$ac_delim
 APR_CONFIG!$APR_CONFIG$ac_delim
+APR_1_CONFIG!$APR_1_CONFIG$ac_delim
 APU_CONFIG!$APU_CONFIG$ac_delim
+APU_1_CONFIG!$APU_1_CONFIG$ac_delim
 with_apache_header!$with_apache_header$ac_delim
 QDEFS!$QDEFS$ac_delim
 DDEFS!$DDEFS$ac_delim
@@ -22858,7 +22916,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 16; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 19; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
