* adding --with-iconv --with-iconv_hook
git-svn-id: http://svn.sourceforge.jp/svnroot/modchxj/mod_chxj/trunk@619 1a406e8e-add9-4483-a2c8-d8cac5b7c224

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1048,7 +1048,8 @@ Optional Packages:
   --with-apache-header=ARG The directory with the header file of apache2.0 is specified.
   --with-apxs=ARG Path of apxs program file.
   --with-apr-config=ARG  Path of apr-config program file.
-  --with-iconv=ARG  specify the place of the libiconv_hook or libiconv library file.
+  --with-iconv=ARG  specify the place of the libiconv directory.
+  --with-iconv_hook=ARG  specify the place of the libiconv_hook directory.
 
 Some influential environment variables:
   CC          C compiler command
@@ -3464,7 +3465,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 3467 "configure"' > conftest.$ac_ext
+  echo '#line 3468 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -4946,7 +4947,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:4949:" \
+echo "$as_me:4950:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -6007,11 +6008,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6010: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6011: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6014: \$? = $ac_status" >&5
+   echo "$as_me:6015: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -6275,11 +6276,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6278: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6279: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6282: \$? = $ac_status" >&5
+   echo "$as_me:6283: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -6379,11 +6380,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6382: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6383: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:6386: \$? = $ac_status" >&5
+   echo "$as_me:6387: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -8737,7 +8738,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8740 "configure"
+#line 8741 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -8837,7 +8838,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8840 "configure"
+#line 8841 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11175,11 +11176,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11178: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11179: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:11182: \$? = $ac_status" >&5
+   echo "$as_me:11183: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -11279,11 +11280,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11282: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11283: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:11286: \$? = $ac_status" >&5
+   echo "$as_me:11287: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -12867,11 +12868,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12870: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12871: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12874: \$? = $ac_status" >&5
+   echo "$as_me:12875: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -12971,11 +12972,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12974: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12975: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12978: \$? = $ac_status" >&5
+   echo "$as_me:12979: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -15194,11 +15195,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15197: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15198: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15201: \$? = $ac_status" >&5
+   echo "$as_me:15202: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -15462,11 +15463,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15465: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15466: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15469: \$? = $ac_status" >&5
+   echo "$as_me:15470: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -15566,11 +15567,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15569: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15570: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:15573: \$? = $ac_status" >&5
+   echo "$as_me:15574: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -18612,7 +18613,19 @@ if test "x$with_apr_config" != "x" ; then
 fi
 
 
-echo "$as_me:$LINENO: checking for iconv_open in -liconv_hook" >&5
+# Check whether --with-iconv or --without-iconv was given.
+if test "${with_iconv+set}" = set; then
+  withval="$with_iconv"
+
+fi;
+
+# Check whether --with-iconv_hook or --without-iconv_hook was given.
+if test "${with_iconv_hook+set}" = set; then
+  withval="$with_iconv_hook"
+
+fi;
+if test "x$with_iconv" = "x" -a "x$with_iconv_hook" = "x" ; then
+  echo "$as_me:$LINENO: checking for iconv_open in -liconv_hook" >&5
 echo $ECHO_N "checking for iconv_open in -liconv_hook... $ECHO_C" >&6
 if test "${ac_cv_lib_iconv_hook_iconv_open+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -18676,16 +18689,17 @@ fi
 echo "$as_me:$LINENO: result: $ac_cv_lib_iconv_hook_iconv_open" >&5
 echo "${ECHO_T}$ac_cv_lib_iconv_hook_iconv_open" >&6
 if test $ac_cv_lib_iconv_hook_iconv_open = yes; then
-  cat >>confdefs.h <<_ACEOF
-#define HAVE_LIBICONV_HOOK 1
+
+      with_iconv="ok"
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_LIBICONV_HOOK
 _ACEOF
 
-  LIBS="-liconv_hook $LIBS"
 
 else
 
-
-echo "$as_me:$LINENO: checking for iconv_open in -liconv" >&5
+    echo "$as_me:$LINENO: checking for iconv_open in -liconv" >&5
 echo $ECHO_N "checking for iconv_open in -liconv... $ECHO_C" >&6
 if test "${ac_cv_lib_iconv_iconv_open+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -18749,41 +18763,80 @@ fi
 echo "$as_me:$LINENO: result: $ac_cv_lib_iconv_iconv_open" >&5
 echo "${ECHO_T}$ac_cv_lib_iconv_iconv_open" >&6
 if test $ac_cv_lib_iconv_iconv_open = yes; then
-  cat >>confdefs.h <<_ACEOF
-#define HAVE_LIBICONV 1
+
+      with_iconv="ok"
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_LIBICONV
 _ACEOF
 
-  LIBS="-liconv $LIBS"
 
 else
 
-    { { echo "$as_me:$LINENO: error: iconv library is not found." >&5
-echo "$as_me: error: iconv library is not found." >&2;}
-   { (exit 1); exit 1; }; }
+      witn_iconv=""
 
 fi
 
 
 fi
 
+fi
 
 if test "x$with_iconv" = "x" ; then
-
-# Check whether --with-iconv or --without-iconv was given.
-if test "${with_iconv+set}" = set; then
-  withval="$with_iconv"
-
-fi;
   if test "x$with_iconv" = "xyes" ; then
       { { echo "$as_me:$LINENO: error:
-  Please specify the --with-iconv option. And, please specify the place of the libiconv_hook or libiconv program.
+  Please specify the --with-iconv option. And, please specify the place of the libiconv program.
   " >&5
 echo "$as_me: error:
-  Please specify the --with-iconv option. And, please specify the place of the libiconv_hook or libiconv program.
+  Please specify the --with-iconv option. And, please specify the place of the libiconv program.
+  " >&2;}
+   { (exit 1); exit 1; }; }
+  fi
+  if test "x$with_iconv" != "x" ; then
+    LIBS="${LIBS} -L$with_iconv -liconv "
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_LIBICONV
+_ACEOF
+
+  fi
+fi
+if test "x$with_iconv" = "x" ; then
+  if test "x$with_iconv_hook" = "xyes" ; then
+      { { echo "$as_me:$LINENO: error:
+  Please specify the --with-iconv-hook option. And, please specify the place of the libiconv_hook program.
+  " >&5
+echo "$as_me: error:
+  Please specify the --with-iconv-hook option. And, please specify the place of the libiconv_hook program.
+  " >&2;}
+   { (exit 1); exit 1; }; }
+  fi
+  if test "x$with_iconv_hook" != "x" ; then
+    LIBS="${LIBS} -L${with_iconv_hook} -liconv_hook "
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_LIBICONV_HOOK
+_ACEOF
+
+  fi
+  if test "x$with_iconv_hook" = "x" ; then
+      { { echo "$as_me:$LINENO: error:
+  Please specify the --with-iconv-hook option. And, please specify the place of the libiconv_hook program.
+  " >&5
+echo "$as_me: error:
+  Please specify the --with-iconv-hook option. And, please specify the place of the libiconv_hook program.
   " >&2;}
    { (exit 1); exit 1; }; }
   fi
 fi
+
+
+case $host_os in
+  freebsd*)
+    CFLAGS="${CFLAGS} -I/usr/local/include "
+    ;;
+esac
+
 
 LIBS="${LIBS} `${WAND_CONFIG} --ldflags` `${WAND_CONFIG} --libs | sed -e s/-ldpstk//` "
 LIBS="${LIBS} `${APR_CONFIG} --ldflags` `${APR_CONFIG} --libs` "
